# Generated by Django 4.0.6 on 2024-06-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0009_alter_director_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='fotografia',
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='director'),
        ),
    ]
