# Generated by Django 4.0.6 on 2024-08-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0011_cine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='portada',
        ),
    ]
